import type { NextPage } from 'next';
import { useRouter } from 'next/router';
import { useEffect } from 'react';
import { useAuthState } from 'react-firebase-hooks/auth';
import { auth, db } from '../../firebase';
import Head from 'next/head';
import {
  authState,
  categoriesState,
  postsState,
  subCategoriesState,
} from '../../store';
import { useRecoilState } from 'recoil';
import {
  collection,
  onSnapshot,
  orderBy,
  query,
  where,
} from 'firebase/firestore';
import { Box, Container } from '@mui/material';

const Home: NextPage = () => {
  const router = useRouter();
  const [currentUser, setCurrentUser] = useRecoilState(authState);
  const [categories, setCategories]: any = useRecoilState(categoriesState); // カテゴリー一覧
  const [subCategories, setSubCategories]: any =
    useRecoilState(subCategoriesState); // サブカテゴリー一覧
  const [posts, setPosts]: any = useRecoilState(postsState); // 記事一覧

  // カテゴリー一覧を取得
  useEffect(() => {
    const q = query(collection(db, 'categories'), orderBy('createdAt', 'desc'));
    onSnapshot(q, (querySnapshot) => {
      setCategories(
        querySnapshot.docs.map((doc) => ({
          ...doc.data(),
          id: doc.id,
        }))
      );
    });
  }, [setCategories]);

  // サブカテゴリー一覧を取得
  useEffect(() => {
    onSnapshot(collection(db, 'subCategories'), (querySnapshot) => {
      setSubCategories(
        querySnapshot.docs.map((doc) => ({
          ...doc.data(),
          id: doc.id,
        }))
      );
    });
  }, [setSubCategories]);

  // 記事一覧を取得
  useEffect(() => {
    onSnapshot(collection(db, 'posts'), (querySnapshot) => {
      setPosts(
        querySnapshot.docs.map((doc) => ({
          ...doc.data(),
          id: doc.id,
        }))
      );
    });
  }, [setPosts]);

  return (
    <div>
      <Head>
        <title>DAIMARU-HAKUI</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Container maxWidth='md'>
        <Box width='100%' sx={{ p: 6, pt: 1, mt: 6, backgroundColor: 'white' }}>
          <Box component='h1'>新着</Box>
          {posts.map((post: { id: string; title: string }) => (
            <Box key={post.id}>{post.title}</Box>
          ))}
        </Box>
      </Container>
    </div>
  );
};

export default Home;
